name: eggplant
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - pip=20.0.2=py37_1
  - setuptools=46.1.3=py37_0
  - wheel=0.34.2=py37_0
  - pip:
    - cycler==0.10.0
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - numpy==1.18.2
    - pandas==1.0.3
    - pika==1.1.0
    - pymongo==3.10.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-dotenv==0.12.0
    - pytz==2019.3
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - six==1.14.0
    - xgboost==1.0.2
# tensorflow
# dill
